FROM rabbitmq:4.1.5-management-alpine

RUN apk add --no-cache curl unzip

RUN curl -L -o rabbitmq_delayed_message_exchange-4.2.0.ez \
    https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.1.0/rabbitmq_delayed_message_exchange-4.1.0.ez && \
    mv rabbitmq_delayed_message_exchange-4.2.0.ez /opt/rabbitmq/plugins/

RUN curl -L -o /tmp/deduplication.zip \
    https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.7.1/plugins-rmqv4.1.x-erl27-elx1.18.zip  && \
    unzip /tmp/deduplication.zip -d /tmp/deduplication && \
    mv /tmp/deduplication/*.ez /opt/rabbitmq/plugins/ && \
    rm -rf /tmp/deduplication.zip /tmp/deduplication 

RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange rabbitmq_message_deduplication
